const mockData = [
  {
    id: 10672763,
    partnership_id: '578',
    partner_data: {
      id: '578',
      name: 'ООО "ГРУЗЧИКОВ-СЕРВИС СПБ"',
      phone: '74951205096'
    },
    date: '2024-11-20 12:35:35',
    date_notime: '2024-11-20',
    time: 0,
    from_number: 'sip**r_**',
    from_extension: '671',
    to_number: '796**36**',
    to_extension: '',
    is_skilla: 0,
    status: 'Не дозвонился',
    record: '',
    line_number: 'sip**se**',
    line_name: '',
    in_out: 0,
    from_site: 0,
    source: '',
    errors: [],
    disconnect_reason: '',
    results: [],
    stages: [],
    abuse: [],
    contact_name: '',
    contact_company: '',
    person_id: 4730,
    person_name: '**',
    person_surname: '**',
    person_avatar: 'https://lk.skilla.ru/img/noavatar.jpg',
    candidate_id: 0,
    candidate_name: '',
    candidate_link: '',
    candidate_vacancy_name: ''
  },
  {
    id: 10672762,
    partnership_id: '578',
    partner_data: {
      id: '578',
      name: 'ООО "ГРУЗЧИКОВ-СЕРВИС СПБ"',
      phone: '74951205096'
    },
    date: '2024-11-20 12:34:19',
    date_notime: '2024-11-20',
    time: 39,
    from_number: 'sip**r_**',
    from_extension: '671',
    to_number: '798**66**',
    to_extension: '',
    is_skilla: 0,
    status: 'Дозвонился',
    record: 'MToxMDA2NzYxNToxNDMwMDM3NzExNzow',
    line_number: 'sip**se**',
    line_name: '',
    in_out: 0,
    from_site: 0,
    source: '',
    errors: [],
    disconnect_reason: '',
    results: [],
    stages: [],
    abuse: [],
    contact_name: '',
    contact_company: '',
    person_id: 4730,
    person_name: '**',
    person_surname: '**',
    person_avatar: 'https://lk.skilla.ru/img/noavatar.jpg',
    candidate_id: 0,
    candidate_name: '',
    candidate_link: '',
    candidate_vacancy_name: ''
  },
  {
    id: 10672745,
    partnership_id: '578',
    partner_data: {
      id: '578',
      name: 'ООО "ГРУЗЧИКОВ-СЕРВИС СПБ"',
      phone: '74951205096'
    },
    date: '2024-11-20 12:33:54',
    date_notime: '2024-11-20',
    time: 8,
    from_number: 'sip**r_**',
    from_extension: '671',
    to_number: '792**02**',
    to_extension: '',
    is_skilla: 0,
    status: 'Дозвонился',
    record: 'MToxMDA2NzYxNToxNDMwMDM3NzExNzow',
    line_number: 'sip**se**',
    line_name: '',
    in_out: 0,
    from_site: 0,
    source: '',
    errors: [],
    disconnect_reason: '',
    results: [],
    stages: [],
    abuse: [],
    contact_name: '',
    contact_company: '',
    person_id: 4730,
    person_name: '**',
    person_surname: '**',
    person_avatar: 'https://lk.skilla.ru/img/noavatar.jpg',
    candidate_id: 0,
    candidate_name: '',
    candidate_link: '',
    candidate_vacancy_name: ''
  },
  {
    id: 10672707,
    partnership_id: '578',
    partner_data: {
      id: '578',
      name: 'ООО "ГРУЗЧИКОВ-СЕРВИС СПБ"',
      phone: '74951205096'
    },
    date: '2024-11-20 12:28:40',
    date_notime: '2024-11-20',
    time: 5,
    from_number: 'sip**r_**',
    from_extension: '671',
    to_number: '792**02**',
    to_extension: '',
    is_skilla: 0,
    status: 'Дозвонился',
    record: 'MToxMDA2NzYxNToxNDMwMDM3NzExNzow',
    line_number: 'sip**se**',
    line_name: '',
    in_out: 0,
    from_site: 0,
    source: '',
    errors: [],
    disconnect_reason: '',
    results: [],
    stages: [],
    abuse: [],
    contact_name: '',
    contact_company: '',
    person_id: 4730,
    person_name: '**',
    person_surname: '**',
    person_avatar: 'https://lk.skilla.ru/img/noavatar.jpg',
    candidate_id: 0,
    candidate_name: '',
    candidate_link: '',
    candidate_vacancy_name: ''
  },
  {
    id: 10672706,
    partnership_id: '578',
    partner_data: {
      id: '578',
      name: 'ООО "ГРУЗЧИКОВ-СЕРВИС СПБ"',
      phone: '74951205096'
    },
    date: '2024-11-20 12:28:14',
    date_notime: '2024-11-20',
    time: 0,
    from_number: 'sip**r_**',
    from_extension: '671',
    to_number: '795**77**',
    to_extension: '',
    is_skilla: 0,
    status: 'Не дозвонился',
    record: '',
    line_number: 'sip**se**',
    line_name: '',
    in_out: 0,
    from_site: 0,
    source: '',
    errors: [],
    disconnect_reason: '',
    results: [],
    stages: [],
    abuse: [],
    contact_name: '',
    contact_company: '',
    person_id: 4730,
    person_name: '**',
    person_surname: '**',
    person_avatar: 'https://lk.skilla.ru/img/noavatar.jpg',
    candidate_id: 0,
    candidate_name: '',
    candidate_link: '',
    candidate_vacancy_name: ''
  },
  {
    id: 10672705,
    partnership_id: '578',
    partner_data: {
      id: '578',
      name: 'ООО "ГРУЗЧИКОВ-СЕРВИС СПБ"',
      phone: '74951205096'
    },
    date: '2024-11-20 12:27:52',
    date_notime: '2024-11-20',
    time: 5,
    from_number: 'sip**r_**',
    from_extension: '671',
    to_number: '798**08**',
    to_extension: '',
    is_skilla: 0,
    status: 'Дозвонился',
    record: 'MToxMDA2NzYxNToxNDMwMDM3NzExNzow',
    line_number: 'sip**se**',
    line_name: '',
    in_out: 0,
    from_site: 0,
    source: '',
    errors: [],
    disconnect_reason: '',
    results: [],
    stages: [],
    abuse: [],
    contact_name: '',
    contact_company: '',
    person_id: 4730,
    person_name: '**',
    person_surname: '**',
    person_avatar: 'https://lk.skilla.ru/img/noavatar.jpg',
    candidate_id: 0,
    candidate_name: '',
    candidate_link: '',
    candidate_vacancy_name: ''
  },
  {
    id: 10672696,
    partnership_id: '578',
    partner_data: {
      id: '578',
      name: 'ООО "ГРУЗЧИКОВ-СЕРВИС СПБ"',
      phone: '74951205096'
    },
    date: '2024-11-20 12:27:05',
    date_notime: '2024-11-20',
    time: 5,
    from_number: 'sip**r_**',
    from_extension: '671',
    to_number: '791**63**',
    to_extension: '',
    is_skilla: 0,
    status: 'Дозвонился',
    record: 'MToxMDA2NzYxNToxNDMwMDM3NzExNzow',
    line_number: 'sip**se**',
    line_name: '',
    in_out: 0,
    from_site: 0,
    source: '',
    errors: [],
    disconnect_reason: '',
    results: [],
    stages: [],
    abuse: [],
    contact_name: '',
    contact_company: '',
    person_id: 4730,
    person_name: '**',
    person_surname: '**',
    person_avatar: 'https://lk.skilla.ru/img/noavatar.jpg',
    candidate_id: 0,
    candidate_name: '',
    candidate_link: '',
    candidate_vacancy_name: ''
  },
  {
    id: 10672695,
    partnership_id: '578',
    partner_data: {
      id: '578',
      name: 'ООО "ГРУЗЧИКОВ-СЕРВИС СПБ"',
      phone: '74951205096'
    },
    date: '2024-11-20 12:26:26',
    date_notime: '2024-11-20',
    time: 3,
    from_number: 'sip**r_**',
    from_extension: '671',
    to_number: '790**59**',
    to_extension: '',
    is_skilla: 0,
    status: 'Дозвонился',
    record: '',
    line_number: 'sip**se**',
    line_name: '',
    in_out: 0,
    from_site: 0,
    source: '',
    errors: [],
    disconnect_reason: '',
    results: [],
    stages: [],
    abuse: [],
    contact_name: '',
    contact_company: '',
    person_id: 4730,
    person_name: '**',
    person_surname: '**',
    person_avatar: 'https://lk.skilla.ru/img/noavatar.jpg',
    candidate_id: 0,
    candidate_name: '',
    candidate_link: '',
    candidate_vacancy_name: ''
  },
  {
    id: 10672694,
    partnership_id: '578',
    partner_data: {
      id: '578',
      name: 'ООО "ГРУЗЧИКОВ-СЕРВИС СПБ"',
      phone: '74951205096'
    },
    date: '2024-11-20 12:25:43',
    date_notime: '2024-11-20',
    time: 0,
    from_number: 'sip**r_**',
    from_extension: '671',
    to_number: '791**43**',
    to_extension: '',
    is_skilla: 0,
    status: 'Не дозвонился',
    record: '',
    line_number: 'sip**se**',
    line_name: '',
    in_out: 0,
    from_site: 0,
    source: '',
    errors: [],
    disconnect_reason: '',
    results: [],
    stages: [],
    abuse: [],
    contact_name: '',
    contact_company: '',
    person_id: 4730,
    person_name: '**',
    person_surname: '**',
    person_avatar: 'https://lk.skilla.ru/img/noavatar.jpg',
    candidate_id: 0,
    candidate_name: '',
    candidate_link: '',
    candidate_vacancy_name: ''
  },
  {
    id: 10672686,
    partnership_id: '578',
    partner_data: {
      id: '578',
      name: 'ООО "ГРУЗЧИКОВ-СЕРВИС СПБ"',
      phone: '74951205096'
    },
    date: '2024-11-20 12:25:19',
    date_notime: '2024-11-20',
    time: 0,
    from_number: 'sip**r_**',
    from_extension: '671',
    to_number: '796**40**',
    to_extension: '',
    is_skilla: 0,
    status: 'Не дозвонился',
    record: '',
    line_number: 'sip**se**',
    line_name: '',
    in_out: 0,
    from_site: 0,
    source: '',
    errors: [],
    disconnect_reason: '',
    results: [],
    stages: [],
    abuse: [],
    contact_name: '',
    contact_company: '',
    person_id: 4730,
    person_name: '**',
    person_surname: '**',
    person_avatar: 'https://lk.skilla.ru/img/noavatar.jpg',
    candidate_id: 0,
    candidate_name: '',
    candidate_link: '',
    candidate_vacancy_name: ''
  },
  {
    id: 10672685,
    partnership_id: '578',
    partner_data: {
      id: '578',
      name: 'ООО "ГРУЗЧИКОВ-СЕРВИС СПБ"',
      phone: '74951205096'
    },
    date: '2024-11-20 12:24:35',
    date_notime: '2024-11-20',
    time: 3,
    from_number: 'sip**r_**',
    from_extension: '671',
    to_number: '790**98**',
    to_extension: '',
    is_skilla: 0,
    status: 'Дозвонился',
    record: '',
    line_number: 'sip**se**',
    line_name: '',
    in_out: 0,
    from_site: 0,
    source: '',
    errors: [],
    disconnect_reason: '',
    results: [],
    stages: [],
    abuse: [],
    contact_name: '',
    contact_company: '',
    person_id: 4730,
    person_name: '**',
    person_surname: '**',
    person_avatar: 'https://lk.skilla.ru/img/noavatar.jpg',
    candidate_id: 0,
    candidate_name: '',
    candidate_link: '',
    candidate_vacancy_name: ''
  },
  {
    id: 10672501,
    partnership_id: '578',
    partner_data: {
      id: '578',
      name: 'ООО "ГРУЗЧИКОВ-СЕРВИС СПБ"',
      phone: '74951205096'
    },
    date: '2024-11-20 12:02:29',
    date_notime: '2024-11-20',
    time: 5,
    from_number: 'sip**r_**',
    from_extension: '671',
    to_number: '798**36**',
    to_extension: '',
    is_skilla: 0,
    status: 'Дозвонился',
    record: '',
    line_number: 'sip**se**',
    line_name: '',
    in_out: 0,
    from_site: 0,
    source: '',
    errors: [],
    disconnect_reason: '',
    results: [],
    stages: [],
    abuse: [],
    contact_name: '',
    contact_company: '',
    person_id: 4730,
    person_name: '**',
    person_surname: '**',
    person_avatar: 'https://lk.skilla.ru/img/noavatar.jpg',
    candidate_id: 0,
    candidate_name: '',
    candidate_link: '',
    candidate_vacancy_name: ''
  },
  {
    id: 10672465,
    partnership_id: '578',
    partner_data: {
      id: '578',
      name: 'ООО "ГРУЗЧИКОВ-СЕРВИС СПБ"',
      phone: '74951205096'
    },
    date: '2024-11-20 12:00:52',
    date_notime: '2024-11-20',
    time: 5,
    from_number: 'sip**r_**',
    from_extension: '671',
    to_number: '791**09**',
    to_extension: '',
    is_skilla: 0,
    status: 'Дозвонился',
    record: 'MToxMDA2NzYxNToxNDMwMDM3NzExNzow',
    line_number: 'sip**se**',
    line_name: '',
    in_out: 0,
    from_site: 0,
    source: '',
    errors: [],
    disconnect_reason: '',
    results: [],
    stages: [],
    abuse: [],
    contact_name: '',
    contact_company: '',
    person_id: 4730,
    person_name: '**',
    person_surname: '**',
    person_avatar: 'https://lk.skilla.ru/img/noavatar.jpg',
    candidate_id: 0,
    candidate_name: '',
    candidate_link: '',
    candidate_vacancy_name: ''
  },
  {
    id: 10672373,
    partnership_id: '578',
    partner_data: {
      id: '578',
      name: 'ООО "ГРУЗЧИКОВ-СЕРВИС СПБ"',
      phone: '74951205096'
    },
    date: '2024-11-20 11:50:29',
    date_notime: '2024-11-20',
    time: 0,
    from_number: 'sip**r_**',
    from_extension: '671',
    to_number: '790**50**',
    to_extension: '',
    is_skilla: 0,
    status: 'Не дозвонился',
    record: '',
    line_number: 'sip**se**',
    line_name: '',
    in_out: 0,
    from_site: 0,
    source: '',
    errors: [],
    disconnect_reason: '',
    results: [],
    stages: [],
    abuse: [],
    contact_name: '',
    contact_company: '',
    person_id: 4730,
    person_name: '**',
    person_surname: '**',
    person_avatar: 'https://lk.skilla.ru/img/noavatar.jpg',
    candidate_id: 0,
    candidate_name: '',
    candidate_link: '',
    candidate_vacancy_name: ''
  },
  {
    id: 10672354,
    partnership_id: '578',
    partner_data: {
      id: '578',
      name: 'ООО "ГРУЗЧИКОВ-СЕРВИС СПБ"',
      phone: '74951205096'
    },
    date: '2024-11-20 11:48:39',
    date_notime: '2024-11-20',
    time: 0,
    from_number: 'sip**r_**',
    from_extension: '671',
    to_number: '790**32**',
    to_extension: '',
    is_skilla: 0,
    status: 'Не дозвонился',
    record: '',
    line_number: 'sip**se**',
    line_name: '',
    in_out: 0,
    from_site: 0,
    source: '',
    errors: [],
    disconnect_reason: '',
    results: [],
    stages: [],
    abuse: [],
    contact_name: '',
    contact_company: '',
    person_id: 4730,
    person_name: '**',
    person_surname: '**',
    person_avatar: 'https://lk.skilla.ru/img/noavatar.jpg',
    candidate_id: 0,
    candidate_name: '',
    candidate_link: '',
    candidate_vacancy_name: ''
  },
  {
    id: 10672341,
    partnership_id: '578',
    partner_data: {
      id: '578',
      name: 'ООО "ГРУЗЧИКОВ-СЕРВИС СПБ"',
      phone: '74951205096'
    },
    date: '2024-11-20 11:47:39',
    date_notime: '2024-11-20',
    time: 0,
    from_number: 'sip**r_**',
    from_extension: '671',
    to_number: '790**31**',
    to_extension: '',
    is_skilla: 0,
    status: 'Не дозвонился',
    record: '',
    line_number: 'sip**se**',
    line_name: '',
    in_out: 0,
    from_site: 0,
    source: '',
    errors: [],
    disconnect_reason: '',
    results: [],
    stages: [],
    abuse: [],
    contact_name: '',
    contact_company: '',
    person_id: 4730,
    person_name: '**',
    person_surname: '**',
    person_avatar: 'https://lk.skilla.ru/img/noavatar.jpg',
    candidate_id: 0,
    candidate_name: '',
    candidate_link: '',
    candidate_vacancy_name: ''
  },
  {
    id: 10672340,
    partnership_id: '578',
    partner_data: {
      id: '578',
      name: 'ООО "ГРУЗЧИКОВ-СЕРВИС СПБ"',
      phone: '74951205096'
    },
    date: '2024-11-20 11:47:00',
    date_notime: '2024-11-20',
    time: 0,
    from_number: 'sip**r_**',
    from_extension: '671',
    to_number: '795**79**',
    to_extension: '',
    is_skilla: 0,
    status: 'Не дозвонился',
    record: '',
    line_number: 'sip**se**',
    line_name: '',
    in_out: 0,
    from_site: 0,
    source: '',
    errors: [],
    disconnect_reason: '',
    results: [],
    stages: [],
    abuse: [],
    contact_name: '',
    contact_company: '',
    person_id: 4730,
    person_name: '**',
    person_surname: '**',
    person_avatar: 'https://lk.skilla.ru/img/noavatar.jpg',
    candidate_id: 0,
    candidate_name: '',
    candidate_link: '',
    candidate_vacancy_name: ''
  },
  {
    id: 10672339,
    partnership_id: '578',
    partner_data: {
      id: '578',
      name: 'ООО "ГРУЗЧИКОВ-СЕРВИС СПБ"',
      phone: '74951205096'
    },
    date: '2024-11-20 11:46:34',
    date_notime: '2024-11-20',
    time: 2,
    from_number: 'sip**r_**',
    from_extension: '671',
    to_number: '799**31**',
    to_extension: '',
    is_skilla: 0,
    status: 'Дозвонился',
    record: '',
    line_number: 'sip**se**',
    line_name: '',
    in_out: 0,
    from_site: 0,
    source: '',
    errors: [],
    disconnect_reason: '',
    results: [],
    stages: [],
    abuse: [],
    contact_name: '',
    contact_company: '',
    person_id: 4730,
    person_name: '**',
    person_surname: '**',
    person_avatar: 'https://lk.skilla.ru/img/noavatar.jpg',
    candidate_id: 0,
    candidate_name: '',
    candidate_link: '',
    candidate_vacancy_name: ''
  },
  {
    id: 10672338,
    partnership_id: '578',
    partner_data: {
      id: '578',
      name: 'ООО "ГРУЗЧИКОВ-СЕРВИС СПБ"',
      phone: '74951205096'
    },
    date: '2024-11-20 11:45:48',
    date_notime: '2024-11-20',
    time: 0,
    from_number: 'sip**r_**',
    from_extension: '671',
    to_number: '790**63**',
    to_extension: '',
    is_skilla: 0,
    status: 'Не дозвонился',
    record: '',
    line_number: 'sip**se**',
    line_name: '',
    in_out: 0,
    from_site: 0,
    source: '',
    errors: [],
    disconnect_reason: '',
    results: [],
    stages: [],
    abuse: [],
    contact_name: '',
    contact_company: '',
    person_id: 4730,
    person_name: '**',
    person_surname: '**',
    person_avatar: 'https://lk.skilla.ru/img/noavatar.jpg',
    candidate_id: 0,
    candidate_name: '',
    candidate_link: '',
    candidate_vacancy_name: ''
  },
  {
    id: 10672097,
    partnership_id: '578',
    partner_data: {
      id: '578',
      name: 'ООО "ГРУЗЧИКОВ-СЕРВИС СПБ"',
      phone: '74951205096'
    },
    date: '2024-11-20 11:19:13',
    date_notime: '2024-11-20',
    time: 0,
    from_number: 'sip**r_**',
    from_extension: '671',
    to_number: '791**69**',
    to_extension: '',
    is_skilla: 0,
    status: 'Не дозвонился',
    record: '',
    line_number: 'sip**se**',
    line_name: '',
    in_out: 0,
    from_site: 0,
    source: '',
    errors: [],
    disconnect_reason: '',
    results: [],
    stages: [],
    abuse: [],
    contact_name: '',
    contact_company: '',
    person_id: 4730,
    person_name: '**',
    person_surname: '**',
    person_avatar: 'https://lk.skilla.ru/img/noavatar.jpg',
    candidate_id: 0,
    candidate_name: '',
    candidate_link: '',
    candidate_vacancy_name: ''
  },
  {
    id: 10672096,
    partnership_id: '578',
    partner_data: {
      id: '578',
      name: 'ООО "ГРУЗЧИКОВ-СЕРВИС СПБ"',
      phone: '74951205096'
    },
    date: '2024-11-20 11:14:44',
    date_notime: '2024-11-20',
    time: 108,
    from_number: 'sip**r_**',
    from_extension: '671',
    to_number: '790**32**',
    to_extension: '',
    is_skilla: 0,
    status: 'Дозвонился',
    record: 'MToxMDA2NzYxNToxNDMwMDM3NzExNzow',
    line_number: 'sip**se**',
    line_name: '',
    in_out: 0,
    from_site: 0,
    source: '',
    errors: [],
    disconnect_reason: '',
    results: [],
    stages: [],
    abuse: [],
    contact_name: '',
    contact_company: '',
    person_id: 4730,
    person_name: '**',
    person_surname: '**',
    person_avatar: 'https://lk.skilla.ru/img/noavatar.jpg',
    candidate_id: 0,
    candidate_name: '',
    candidate_link: '',
    candidate_vacancy_name: ''
  },
  {
    id: 10671975,
    partnership_id: '578',
    partner_data: {
      id: '578',
      name: 'ООО "ГРУЗЧИКОВ-СЕРВИС СПБ"',
      phone: '74951205096'
    },
    date: '2024-11-20 11:04:41',
    date_notime: '2024-11-20',
    time: 0,
    from_number: 'sip**r_**',
    from_extension: '671',
    to_number: '791**26**',
    to_extension: '',
    is_skilla: 0,
    status: 'Не дозвонился',
    record: '',
    line_number: 'sip**se**',
    line_name: '',
    in_out: 0,
    from_site: 0,
    source: '',
    errors: [],
    disconnect_reason: '',
    results: [],
    stages: [],
    abuse: [],
    contact_name: '',
    contact_company: '',
    person_id: 4730,
    person_name: '**',
    person_surname: '**',
    person_avatar: 'https://lk.skilla.ru/img/noavatar.jpg',
    candidate_id: 0,
    candidate_name: '',
    candidate_link: '',
    candidate_vacancy_name: ''
  },
  {
    id: 10671943,
    partnership_id: '578',
    partner_data: {
      id: '578',
      name: 'ООО "ГРУЗЧИКОВ-СЕРВИС СПБ"',
      phone: '74951205096'
    },
    date: '2024-11-20 10:59:32',
    date_notime: '2024-11-20',
    time: 157,
    from_number: 'sip**r_**',
    from_extension: '671',
    to_number: '798**50**',
    to_extension: '',
    is_skilla: 0,
    status: 'Дозвонился',
    record: 'MToxMDA2NzYxNToxNDMwMDM3NzExNzow',
    line_number: 'sip**se**',
    line_name: '',
    in_out: 0,
    from_site: 0,
    source: '',
    errors: [],
    disconnect_reason: '',
    results: [],
    stages: [],
    abuse: [],
    contact_name: '',
    contact_company: '',
    person_id: 4730,
    person_name: '**',
    person_surname: '**',
    person_avatar: 'https://lk.skilla.ru/img/noavatar.jpg',
    candidate_id: 0,
    candidate_name: '',
    candidate_link: '',
    candidate_vacancy_name: ''
  },
  {
    id: 10671882,
    partnership_id: '578',
    partner_data: {
      id: '578',
      name: 'ООО "ГРУЗЧИКОВ-СЕРВИС СПБ"',
      phone: '74951205096'
    },
    date: '2024-11-20 10:52:43',
    date_notime: '2024-11-20',
    time: 5,
    from_number: 'sip**r_**',
    from_extension: '671',
    to_number: '791**04**',
    to_extension: '',
    is_skilla: 0,
    status: 'Дозвонился',
    record: 'MToxMDA2NzYxNToxNDMwMDM3NzExNzow',
    line_number: 'sip**se**',
    line_name: '',
    in_out: 0,
    from_site: 0,
    source: '',
    errors: [],
    disconnect_reason: '',
    results: [],
    stages: [],
    abuse: [],
    contact_name: '',
    contact_company: '',
    person_id: 4730,
    person_name: '**',
    person_surname: '**',
    person_avatar: 'https://lk.skilla.ru/img/noavatar.jpg',
    candidate_id: 0,
    candidate_name: '',
    candidate_link: '',
    candidate_vacancy_name: ''
  },
  {
    id: 10671878,
    partnership_id: '578',
    partner_data: {
      id: '578',
      name: 'ООО "ГРУЗЧИКОВ-СЕРВИС СПБ"',
      phone: '74951205096'
    },
    date: '2024-11-20 10:51:59',
    date_notime: '2024-11-20',
    time: 0,
    from_number: 'sip**r_**',
    from_extension: '671',
    to_number: '795**15**',
    to_extension: '',
    is_skilla: 0,
    status: 'Не дозвонился',
    record: '',
    line_number: 'sip**se**',
    line_name: '',
    in_out: 0,
    from_site: 0,
    source: '',
    errors: [],
    disconnect_reason: '',
    results: [],
    stages: [],
    abuse: [],
    contact_name: '',
    contact_company: '',
    person_id: 4730,
    person_name: '**',
    person_surname: '**',
    person_avatar: 'https://lk.skilla.ru/img/noavatar.jpg',
    candidate_id: 0,
    candidate_name: '',
    candidate_link: '',
    candidate_vacancy_name: ''
  },
  {
    id: 10671852,
    partnership_id: '578',
    partner_data: {
      id: '578',
      name: 'ООО "ГРУЗЧИКОВ-СЕРВИС СПБ"',
      phone: '74951205096'
    },
    date: '2024-11-20 10:51:30',
    date_notime: '2024-11-20',
    time: 4,
    from_number: 'sip**r_**',
    from_extension: '671',
    to_number: '799**95**',
    to_extension: '',
    is_skilla: 0,
    status: 'Дозвонился',
    record: '',
    line_number: 'sip**se**',
    line_name: '',
    in_out: 0,
    from_site: 0,
    source: '',
    errors: [],
    disconnect_reason: '',
    results: [],
    stages: [],
    abuse: [],
    contact_name: '',
    contact_company: '',
    person_id: 4730,
    person_name: '**',
    person_surname: '**',
    person_avatar: 'https://lk.skilla.ru/img/noavatar.jpg',
    candidate_id: 0,
    candidate_name: '',
    candidate_link: '',
    candidate_vacancy_name: ''
  },
  {
    id: 10671851,
    partnership_id: '578',
    partner_data: {
      id: '578',
      name: 'ООО "ГРУЗЧИКОВ-СЕРВИС СПБ"',
      phone: '74951205096'
    },
    date: '2024-11-20 10:50:27',
    date_notime: '2024-11-20',
    time: 3,
    from_number: 'sip**r_**',
    from_extension: '671',
    to_number: '799**75**',
    to_extension: '',
    is_skilla: 0,
    status: 'Дозвонился',
    record: '',
    line_number: 'sip**se**',
    line_name: '',
    in_out: 0,
    from_site: 0,
    source: '',
    errors: [],
    disconnect_reason: '',
    results: [],
    stages: [],
    abuse: [],
    contact_name: '',
    contact_company: '',
    person_id: 4730,
    person_name: '**',
    person_surname: '**',
    person_avatar: 'https://lk.skilla.ru/img/noavatar.jpg',
    candidate_id: 0,
    candidate_name: '',
    candidate_link: '',
    candidate_vacancy_name: ''
  },
  {
    id: 10671812,
    partnership_id: '578',
    partner_data: {
      id: '578',
      name: 'ООО "ГРУЗЧИКОВ-СЕРВИС СПБ"',
      phone: '74951205096'
    },
    date: '2024-11-20 10:44:38',
    date_notime: '2024-11-20',
    time: 0,
    from_number: 'sip**ha**',
    from_extension: '103',
    to_number: '790**42**',
    to_extension: '',
    is_skilla: 0,
    status: 'Не дозвонился',
    record: '',
    line_number: 'sip**se**',
    line_name: '',
    in_out: 0,
    from_site: 0,
    source: '',
    errors: [],
    disconnect_reason: '',
    results: [],
    stages: [],
    abuse: [],
    contact_name: '',
    contact_company: '',
    person_id: 3487,
    person_name: '**',
    person_surname: '**',
    person_avatar: 'https://lk.skilla.ru/img/noavatar.jpg',
    candidate_id: 0,
    candidate_name: '',
    candidate_link: '',
    candidate_vacancy_name: ''
  },
  {
    id: 10671772,
    partnership_id: '578',
    partner_data: {
      id: '578',
      name: 'ООО "ГРУЗЧИКОВ-СЕРВИС СПБ"',
      phone: '74951205096'
    },
    date: '2024-11-20 10:35:29',
    date_notime: '2024-11-20',
    time: 0,
    from_number: 'sip**ha**',
    from_extension: '103',
    to_number: '790**42**',
    to_extension: '',
    is_skilla: 0,
    status: 'Не дозвонился',
    record: '',
    line_number: 'sip**se**',
    line_name: '',
    in_out: 0,
    from_site: 0,
    source: '',
    errors: [],
    disconnect_reason: '',
    results: [],
    stages: [],
    abuse: [],
    contact_name: '',
    contact_company: '',
    person_id: 3487,
    person_name: '**',
    person_surname: '**',
    person_avatar: 'https://lk.skilla.ru/img/noavatar.jpg',
    candidate_id: 0,
    candidate_name: '',
    candidate_link: '',
    candidate_vacancy_name: ''
  },
  {
    id: 10670654,
    partnership_id: '578',
    partner_data: {
      id: '578',
      name: 'ООО "ГРУЗЧИКОВ-СЕРВИС СПБ"',
      phone: '74951205096'
    },
    date: '2024-11-19 17:40:40',
    date_notime: '2024-11-19',
    time: 22,
    from_number: 'sip**r_**',
    from_extension: '671',
    to_number: '793**75**',
    to_extension: '',
    is_skilla: 0,
    status: 'Дозвонился',
    record: 'MToxMDA2NzYxNToxNDMwMDM3NzExNzow',
    line_number: 'sip**se**',
    line_name: '',
    in_out: 0,
    from_site: 0,
    source: '',
    errors: [],
    disconnect_reason: '',
    results: [],
    stages: [],
    abuse: [],
    contact_name: '',
    contact_company: '',
    person_id: 4730,
    person_name: '**',
    person_surname: '**',
    person_avatar: 'https://lk.skilla.ru/img/noavatar.jpg',
    candidate_id: 0,
    candidate_name: '',
    candidate_link: '',
    candidate_vacancy_name: ''
  },
  {
    id: 10670324,
    partnership_id: '578',
    partner_data: {
      id: '578',
      name: 'ООО "ГРУЗЧИКОВ-СЕРВИС СПБ"',
      phone: '74951205096'
    },
    date: '2024-11-19 16:30:00',
    date_notime: '2024-11-19',
    time: 0,
    from_number: 'sip**r_**',
    from_extension: '671',
    to_number: '796**73**',
    to_extension: '',
    is_skilla: 0,
    status: 'Не дозвонился',
    record: '',
    line_number: 'sip**se**',
    line_name: '',
    in_out: 0,
    from_site: 0,
    source: '',
    errors: [],
    disconnect_reason: '',
    results: [],
    stages: [],
    abuse: [],
    contact_name: '',
    contact_company: '',
    person_id: 4730,
    person_name: '**',
    person_surname: '**',
    person_avatar: 'https://lk.skilla.ru/img/noavatar.jpg',
    candidate_id: 0,
    candidate_name: '',
    candidate_link: '',
    candidate_vacancy_name: ''
  },
  {
    id: 10670323,
    partnership_id: '578',
    partner_data: {
      id: '578',
      name: 'ООО "ГРУЗЧИКОВ-СЕРВИС СПБ"',
      phone: '74951205096'
    },
    date: '2024-11-19 16:28:11',
    date_notime: '2024-11-19',
    time: 55,
    from_number: 'sip**r_**',
    from_extension: '671',
    to_number: '799**23**',
    to_extension: '',
    is_skilla: 0,
    status: 'Дозвонился',
    record: 'MToxMDA2NzYxNToxNDMwMDM3NzExNzow',
    line_number: 'sip**se**',
    line_name: '',
    in_out: 0,
    from_site: 0,
    source: '',
    errors: [],
    disconnect_reason: '',
    results: [],
    stages: [],
    abuse: [],
    contact_name: '',
    contact_company: '',
    person_id: 4730,
    person_name: '**',
    person_surname: '**',
    person_avatar: 'https://lk.skilla.ru/img/noavatar.jpg',
    candidate_id: 0,
    candidate_name: '',
    candidate_link: '',
    candidate_vacancy_name: ''
  },
  {
    id: 10670255,
    partnership_id: '578',
    partner_data: {
      id: '578',
      name: 'ООО "ГРУЗЧИКОВ-СЕРВИС СПБ"',
      phone: '74951205096'
    },
    date: '2024-11-19 16:23:44',
    date_notime: '2024-11-19',
    time: 117,
    from_number: 'sip**r_**',
    from_extension: '671',
    to_number: '796**44**',
    to_extension: '',
    is_skilla: 0,
    status: 'Дозвонился',
    record: 'MToxMDA2NzYxNToxNDMwMDM3NzExNzow',
    line_number: 'sip**se**',
    line_name: '',
    in_out: 0,
    from_site: 0,
    source: '',
    errors: [],
    disconnect_reason: '',
    results: [],
    stages: [],
    abuse: [],
    contact_name: '',
    contact_company: '',
    person_id: 4730,
    person_name: '**',
    person_surname: '**',
    person_avatar: 'https://lk.skilla.ru/img/noavatar.jpg',
    candidate_id: 0,
    candidate_name: '',
    candidate_link: '',
    candidate_vacancy_name: ''
  },
  {
    id: 10670254,
    partnership_id: '578',
    partner_data: {
      id: '578',
      name: 'ООО "ГРУЗЧИКОВ-СЕРВИС СПБ"',
      phone: '74951205096'
    },
    date: '2024-11-19 16:21:50',
    date_notime: '2024-11-19',
    time: 24,
    from_number: 'sip**r_**',
    from_extension: '671',
    to_number: '792**89**',
    to_extension: '',
    is_skilla: 0,
    status: 'Дозвонился',
    record: 'MToxMDA2NzYxNToxNDMwMDM3NzExNzow',
    line_number: 'sip**se**',
    line_name: '',
    in_out: 0,
    from_site: 0,
    source: '',
    errors: [],
    disconnect_reason: '',
    results: [],
    stages: [],
    abuse: [],
    contact_name: '',
    contact_company: '',
    person_id: 4730,
    person_name: '**',
    person_surname: '**',
    person_avatar: 'https://lk.skilla.ru/img/noavatar.jpg',
    candidate_id: 0,
    candidate_name: '',
    candidate_link: '',
    candidate_vacancy_name: ''
  },
  {
    id: 10670243,
    partnership_id: '578',
    partner_data: {
      id: '578',
      name: 'ООО "ГРУЗЧИКОВ-СЕРВИС СПБ"',
      phone: '74951205096'
    },
    date: '2024-11-19 16:20:38',
    date_notime: '2024-11-19',
    time: 0,
    from_number: 'sip**r_**',
    from_extension: '671',
    to_number: '790**97**',
    to_extension: '',
    is_skilla: 0,
    status: 'Не дозвонился',
    record: '',
    line_number: 'sip**se**',
    line_name: '',
    in_out: 0,
    from_site: 0,
    source: '',
    errors: [],
    disconnect_reason: '',
    results: [],
    stages: [],
    abuse: [],
    contact_name: '',
    contact_company: '',
    person_id: 4730,
    person_name: '**',
    person_surname: '**',
    person_avatar: 'https://lk.skilla.ru/img/noavatar.jpg',
    candidate_id: 0,
    candidate_name: '',
    candidate_link: '',
    candidate_vacancy_name: ''
  },
  {
    id: 10670123,
    partnership_id: '578',
    partner_data: {
      id: '578',
      name: 'ООО "ГРУЗЧИКОВ-СЕРВИС СПБ"',
      phone: '74951205096'
    },
    date: '2024-11-19 15:53:29',
    date_notime: '2024-11-19',
    time: 0,
    from_number: 'sip**r_**',
    from_extension: '671',
    to_number: '799**23**',
    to_extension: '',
    is_skilla: 0,
    status: 'Не дозвонился',
    record: '',
    line_number: '**',
    line_name: '',
    in_out: 0,
    from_site: 0,
    source: '',
    errors: [],
    disconnect_reason: '',
    results: [],
    stages: [],
    abuse: [],
    contact_name: '',
    contact_company: '',
    person_id: 4730,
    person_name: '**',
    person_surname: '**',
    person_avatar: 'https://lk.skilla.ru/img/noavatar.jpg',
    candidate_id: 0,
    candidate_name: '',
    candidate_link: '',
    candidate_vacancy_name: ''
  },
  {
    id: 10669831,
    partnership_id: '578',
    partner_data: {
      id: '578',
      name: 'ООО "ГРУЗЧИКОВ-СЕРВИС СПБ"',
      phone: '74951205096'
    },
    date: '2024-11-19 14:54:11',
    date_notime: '2024-11-19',
    time: 6,
    from_number: 'sip**r_**',
    from_extension: '671',
    to_number: '791**86**',
    to_extension: '',
    is_skilla: 0,
    status: 'Дозвонился',
    record: 'MToxMDA2NzYxNToxNDMwMDM3NzExNzow',
    line_number: 'sip**se**',
    line_name: '',
    in_out: 0,
    from_site: 0,
    source: '',
    errors: [],
    disconnect_reason: '',
    results: [],
    stages: [],
    abuse: [],
    contact_name: '',
    contact_company: '',
    person_id: 4730,
    person_name: '**',
    person_surname: '**',
    person_avatar: 'https://lk.skilla.ru/img/noavatar.jpg',
    candidate_id: 0,
    candidate_name: '',
    candidate_link: '',
    candidate_vacancy_name: ''
  },
  {
    id: 10669830,
    partnership_id: '578',
    partner_data: {
      id: '578',
      name: 'ООО "ГРУЗЧИКОВ-СЕРВИС СПБ"',
      phone: '74951205096'
    },
    date: '2024-11-19 14:53:53',
    date_notime: '2024-11-19',
    time: 15,
    from_number: 'sip**ha**',
    from_extension: '103',
    to_number: '792**11**',
    to_extension: '',
    is_skilla: 0,
    status: 'Дозвонился',
    record: 'MToxMDA2NzYxNToxNDMwMDM3NzExNzow',
    line_number: 'sip**se**',
    line_name: '',
    in_out: 0,
    from_site: 0,
    source: '',
    errors: [],
    disconnect_reason: '',
    results: [],
    stages: [],
    abuse: [],
    contact_name: '',
    contact_company: '',
    person_id: 3487,
    person_name: '**',
    person_surname: '**',
    person_avatar: 'https://lk.skilla.ru/img/noavatar.jpg',
    candidate_id: 0,
    candidate_name: '',
    candidate_link: '',
    candidate_vacancy_name: ''
  },
  {
    id: 10669829,
    partnership_id: '578',
    partner_data: {
      id: '578',
      name: 'ООО "ГРУЗЧИКОВ-СЕРВИС СПБ"',
      phone: '74951205096'
    },
    date: '2024-11-19 14:53:27',
    date_notime: '2024-11-19',
    time: 0,
    from_number: 'sip**r_**',
    from_extension: '671',
    to_number: '790**08**',
    to_extension: '',
    is_skilla: 0,
    status: 'Не дозвонился',
    record: '',
    line_number: 'sip**se**',
    line_name: '',
    in_out: 0,
    from_site: 0,
    source: '',
    errors: [],
    disconnect_reason: '',
    results: [],
    stages: [],
    abuse: [],
    contact_name: '',
    contact_company: '',
    person_id: 4730,
    person_name: '**',
    person_surname: '**',
    person_avatar: 'https://lk.skilla.ru/img/noavatar.jpg',
    candidate_id: 0,
    candidate_name: '',
    candidate_link: '',
    candidate_vacancy_name: ''
  },
  {
    id: 10669758,
    partnership_id: '578',
    partner_data: {
      id: '578',
      name: 'ООО "ГРУЗЧИКОВ-СЕРВИС СПБ"',
      phone: '74951205096'
    },
    date: '2024-11-19 14:37:50',
    date_notime: '2024-11-19',
    time: 3,
    from_number: 'sip**r_**',
    from_extension: '671',
    to_number: '795**68**',
    to_extension: '',
    is_skilla: 0,
    status: 'Дозвонился',
    record: '',
    line_number: 'sip**se**',
    line_name: '',
    in_out: 0,
    from_site: 0,
    source: '',
    errors: [],
    disconnect_reason: '',
    results: [],
    stages: [],
    abuse: [],
    contact_name: '',
    contact_company: '',
    person_id: 4730,
    person_name: '**',
    person_surname: '**',
    person_avatar: 'https://lk.skilla.ru/img/noavatar.jpg',
    candidate_id: 0,
    candidate_name: '',
    candidate_link: '',
    candidate_vacancy_name: ''
  },
  {
    id: 10669757,
    partnership_id: '578',
    partner_data: {
      id: '578',
      name: 'ООО "ГРУЗЧИКОВ-СЕРВИС СПБ"',
      phone: '74951205096'
    },
    date: '2024-11-19 14:36:56',
    date_notime: '2024-11-19',
    time: 5,
    from_number: 'sip**r_**',
    from_extension: '671',
    to_number: '791**38**',
    to_extension: '',
    is_skilla: 0,
    status: 'Дозвонился',
    record: 'MToxMDA2NzYxNToxNDMwMDM3NzExNzow',
    line_number: 'sip**se**',
    line_name: '',
    in_out: 0,
    from_site: 0,
    source: '',
    errors: [],
    disconnect_reason: '',
    results: [],
    stages: [],
    abuse: [],
    contact_name: '',
    contact_company: '',
    person_id: 4730,
    person_name: '**',
    person_surname: '**',
    person_avatar: 'https://lk.skilla.ru/img/noavatar.jpg',
    candidate_id: 0,
    candidate_name: '',
    candidate_link: '',
    candidate_vacancy_name: ''
  },
  {
    id: 10669741,
    partnership_id: '578',
    partner_data: {
      id: '578',
      name: 'ООО "ГРУЗЧИКОВ-СЕРВИС СПБ"',
      phone: '74951205096'
    },
    date: '2024-11-19 14:35:36',
    date_notime: '2024-11-19',
    time: 4,
    from_number: 'sip**r_**',
    from_extension: '671',
    to_number: '791**44**',
    to_extension: '',
    is_skilla: 0,
    status: 'Дозвонился',
    record: '',
    line_number: 'sip**se**',
    line_name: '',
    in_out: 0,
    from_site: 0,
    source: '',
    errors: [],
    disconnect_reason: '',
    results: [],
    stages: [],
    abuse: [],
    contact_name: '',
    contact_company: '',
    person_id: 4730,
    person_name: '**',
    person_surname: '**',
    person_avatar: 'https://lk.skilla.ru/img/noavatar.jpg',
    candidate_id: 0,
    candidate_name: '',
    candidate_link: '',
    candidate_vacancy_name: ''
  },
  {
    id: 10669740,
    partnership_id: '578',
    partner_data: {
      id: '578',
      name: 'ООО "ГРУЗЧИКОВ-СЕРВИС СПБ"',
      phone: '74951205096'
    },
    date: '2024-11-19 14:34:49',
    date_notime: '2024-11-19',
    time: 5,
    from_number: 'sip**r_**',
    from_extension: '671',
    to_number: '791**07**',
    to_extension: '',
    is_skilla: 0,
    status: 'Дозвонился',
    record: 'MToxMDA2NzYxNToxNDMwMDM3NzExNzow',
    line_number: 'sip**se**',
    line_name: '',
    in_out: 0,
    from_site: 0,
    source: '',
    errors: [],
    disconnect_reason: '',
    results: [],
    stages: [],
    abuse: [],
    contact_name: '',
    contact_company: '',
    person_id: 4730,
    person_name: '**',
    person_surname: '**',
    person_avatar: 'https://lk.skilla.ru/img/noavatar.jpg',
    candidate_id: 0,
    candidate_name: '',
    candidate_link: '',
    candidate_vacancy_name: ''
  },
  {
    id: 10669739,
    partnership_id: '578',
    partner_data: {
      id: '578',
      name: 'ООО "ГРУЗЧИКОВ-СЕРВИС СПБ"',
      phone: '74951205096'
    },
    date: '2024-11-19 14:34:09',
    date_notime: '2024-11-19',
    time: 0,
    from_number: 'sip**r_**',
    from_extension: '671',
    to_number: '792**38**',
    to_extension: '',
    is_skilla: 0,
    status: 'Не дозвонился',
    record: '',
    line_number: 'sip**se**',
    line_name: '',
    in_out: 0,
    from_site: 0,
    source: '',
    errors: [],
    disconnect_reason: '',
    results: [],
    stages: [],
    abuse: [],
    contact_name: '',
    contact_company: '',
    person_id: 4730,
    person_name: '**',
    person_surname: '**',
    person_avatar: 'https://lk.skilla.ru/img/noavatar.jpg',
    candidate_id: 0,
    candidate_name: '',
    candidate_link: '',
    candidate_vacancy_name: ''
  },
  {
    id: 10669697,
    partnership_id: '578',
    partner_data: {
      id: '578',
      name: 'ООО "ГРУЗЧИКОВ-СЕРВИС СПБ"',
      phone: '74951205096'
    },
    date: '2024-11-19 14:23:18',
    date_notime: '2024-11-19',
    time: 79,
    from_number: 'sip**ha**',
    from_extension: '103',
    to_number: '792**11**',
    to_extension: '',
    is_skilla: 0,
    status: 'Дозвонился',
    record: 'MToxMDA2NzYxNToxNDMwMDM3NzExNzow',
    line_number: 'sip**se**',
    line_name: '',
    in_out: 0,
    from_site: 0,
    source: '',
    errors: [],
    disconnect_reason: '',
    results: [],
    stages: [],
    abuse: [],
    contact_name: '',
    contact_company: '',
    person_id: 3487,
    person_name: '**',
    person_surname: '**',
    person_avatar: 'https://lk.skilla.ru/img/noavatar.jpg',
    candidate_id: 0,
    candidate_name: '',
    candidate_link: '',
    candidate_vacancy_name: ''
  },
  {
    id: 10669686,
    partnership_id: '578',
    partner_data: {
      id: '578',
      name: 'ООО "ГРУЗЧИКОВ-СЕРВИС СПБ"',
      phone: '74951205096'
    },
    date: '2024-11-19 14:22:42',
    date_notime: '2024-11-19',
    time: 0,
    from_number: 'sip**ha**',
    from_extension: '103',
    to_number: '792**11**',
    to_extension: '',
    is_skilla: 0,
    status: 'Не дозвонился',
    record: '',
    line_number: 'sip**se**',
    line_name: '',
    in_out: 0,
    from_site: 0,
    source: '',
    errors: [],
    disconnect_reason: '',
    results: [],
    stages: [],
    abuse: [],
    contact_name: '',
    contact_company: '',
    person_id: 3487,
    person_name: '**',
    person_surname: '**',
    person_avatar: 'https://lk.skilla.ru/img/noavatar.jpg',
    candidate_id: 0,
    candidate_name: '',
    candidate_link: '',
    candidate_vacancy_name: ''
  },
  {
    id: 10669475,
    partnership_id: '578',
    partner_data: {
      id: '578',
      name: 'ООО "ГРУЗЧИКОВ-СЕРВИС СПБ"',
      phone: '74951205096'
    },
    date: '2024-11-19 13:44:52',
    date_notime: '2024-11-19',
    time: 0,
    from_number: 'sip**r_**',
    from_extension: '671',
    to_number: '790**26**',
    to_extension: '',
    is_skilla: 0,
    status: 'Не дозвонился',
    record: '',
    line_number: 'sip**se**',
    line_name: '',
    in_out: 0,
    from_site: 0,
    source: '',
    errors: [],
    disconnect_reason: '',
    results: [],
    stages: [],
    abuse: [],
    contact_name: '',
    contact_company: '',
    person_id: 4730,
    person_name: '**',
    person_surname: '**',
    person_avatar: 'https://lk.skilla.ru/img/noavatar.jpg',
    candidate_id: 0,
    candidate_name: '',
    candidate_link: '',
    candidate_vacancy_name: ''
  },
  {
    id: 10669474,
    partnership_id: '578',
    partner_data: {
      id: '578',
      name: 'ООО "ГРУЗЧИКОВ-СЕРВИС СПБ"',
      phone: '74951205096'
    },
    date: '2024-11-19 13:44:32',
    date_notime: '2024-11-19',
    time: 0,
    from_number: 'sip**r_**',
    from_extension: '671',
    to_number: '791**29**',
    to_extension: '',
    is_skilla: 0,
    status: 'Не дозвонился',
    record: '',
    line_number: 'sip**se**',
    line_name: '',
    in_out: 0,
    from_site: 0,
    source: '',
    errors: [],
    disconnect_reason: '',
    results: [],
    stages: [],
    abuse: [],
    contact_name: '',
    contact_company: '',
    person_id: 4730,
    person_name: '**',
    person_surname: '**',
    person_avatar: 'https://lk.skilla.ru/img/noavatar.jpg',
    candidate_id: 0,
    candidate_name: '',
    candidate_link: '',
    candidate_vacancy_name: ''
  },
  {
    id: 10669434,
    partnership_id: '578',
    partner_data: {
      id: '578',
      name: 'ООО "ГРУЗЧИКОВ-СЕРВИС СПБ"',
      phone: '74951205096'
    },
    date: '2024-11-19 13:44:15',
    date_notime: '2024-11-19',
    time: 5,
    from_number: 'sip**r_**',
    from_extension: '671',
    to_number: '791**79**',
    to_extension: '',
    is_skilla: 0,
    status: 'Дозвонился',
    record: 'MToxMDA2NzYxNToxNDMwMDM3NzExNzow',
    line_number: 'sip**se**',
    line_name: '',
    in_out: 0,
    from_site: 0,
    source: '',
    errors: [],
    disconnect_reason: '',
    results: [],
    stages: [],
    abuse: [],
    contact_name: '',
    contact_company: '',
    person_id: 4730,
    person_name: '**',
    person_surname: '**',
    person_avatar: 'https://lk.skilla.ru/img/noavatar.jpg',
    candidate_id: 0,
    candidate_name: '',
    candidate_link: '',
    candidate_vacancy_name: ''
  },
  {
    id: 10669433,
    partnership_id: '578',
    partner_data: {
      id: '578',
      name: 'ООО "ГРУЗЧИКОВ-СЕРВИС СПБ"',
      phone: '74951205096'
    },
    date: '2024-11-19 13:44:02',
    date_notime: '2024-11-19',
    time: 0,
    from_number: 'sip**r_**',
    from_extension: '671',
    to_number: '797**52**',
    to_extension: '',
    is_skilla: 0,
    status: 'Не дозвонился',
    record: '',
    line_number: 'sip**se**',
    line_name: '',
    in_out: 0,
    from_site: 0,
    source: '',
    errors: [],
    disconnect_reason: '',
    results: [],
    stages: [],
    abuse: [],
    contact_name: '',
    contact_company: '',
    person_id: 4730,
    person_name: '**',
    person_surname: '**',
    person_avatar: 'https://lk.skilla.ru/img/noavatar.jpg',
    candidate_id: 0,
    candidate_name: '',
    candidate_link: '',
    candidate_vacancy_name: ''
  }
]
